### ISSUE TITLE
Module augmentation shows errors that bare typescript doesn't

### ISSUE THREAD

**Issue by Tragetaschen** [s-panferov/awesome-typescript-loader#205]
Repro: https://github.com/Tragetaschen/awesome-typescript-loader-module-augmentation

I am trying to temporarily fix an bug in the d3-v4 `@types/d3-shape` by augmenting the `d3-shape` module with another member in a local `.d.ts` file.

Typescript is fine with this (`tsc -p .`).

Invoking TypeScript through webpack and awesome-typescript-loader  on the other hand shows

```
ERROR in [default] C:\Users\kairu\Source\Repos\awesome-typescript-loader-module-augmentation\main.ts:1:15
Module '"C:/Users/kairu/Source/Repos/awesome-typescript-loader-module-augmentation/node_modules/@types/d3-shape/index"' has no exported member 'curveStepAfter'.

ERROR in [default] d3-fixup.d.ts:1:29
Cannot find module 'd3-shape'.
```

As you can see, I'm running on Windows. Node is `v6.1.0` and npm `3.8.6`.

**Comment by s-panferov** [comment]
@Tragetaschen  Thanks for the repro example, I'll take a look

**Comment by thrandre** [comment]
I'm having a somewhat similar issue with react and react-dom.

```
ERROR in [default] C:\Projects\Prover-hoved\src\UDIR.Prover.Frontend\node_modules\@types\react-dom\react-dom.server.d.ts:2:30        
Cannot find module 'react'. 
```

I'm guessing this is the culprit (from `@types/react-dom/react-dom.server.d.ts`):
```
declare module "react-dom/server" {
	import { ReactElement } from 'react'; // This should point to typings at @types/react
	
...
}
```

No compilation issues when using version prior to 2.0.3 (2.0.2 works like a charm) or when using `tsc` directly.

My `tsconfig.json` (for completeness):
```
{
	"version": "2.0",
	"compilerOptions": {
		"target": "es2015",
		"noImplicitAny": true,
		"jsx": "react",
		"sourceMap": true,
		"moduleResolution": "node",
		"allowSyntheticDefaultImports": true,
		"paths": {
			"common/components/*": ["./common/components/*"]
		},
		"baseUrl": ""
	},
	"awesomeTypescriptLoaderOptions": {
		"useBabel": true,
		"useCache": true
	},
	"exclude": [
		"node_modules"
	]
}
```

Thanks!

**Comment by s-panferov** [comment]
@Tragetaschen should be fixed in v2.2.0

**Comment by Tragetaschen** [comment]
Hmm, my reproduction still fails on my machine. The errors are reversed, though:
```
Hash: e2e2cd05bd0594692276
Version: webpack 2.1.0-beta.20
Time: 1250ms
  Asset     Size  Chunks             Chunk Names
main.js  89.2 kB       0  [emitted]  main
    + 51 hidden modules

ERROR in [default] C:\Users\kairu\Source\Repos\awesome-typescript-loader-module-augmentation\d3-fixup.d.ts:1:29
Cannot find module 'd3-shape'.

ERROR in [default] C:\Users\kairu\Source\Repos\awesome-typescript-loader-module-augmentation\main.ts:1:15
Module '"C:/Users/kairu/Source/Repos/awesome-typescript-loader-module-augmentation/node_modules/@types/d3-shape/index"' has no exported member 'curveStepAfter'.
```

**Comment by s-panferov** [comment]
It seems that I need to test this on windows.

**Comment by trevorsg** [comment]
I'm running into the exact same issue as @thrandre on 2.1.1.

**Comment by krokofant** [comment]
I'm having the same error as @thrandre on atl 2.2.4 and ts 2.0.3
