### ISSUE TITLE
'cannot find namespace ts' in version 3.0.0-beta.14

### ISSUE THREAD

**Issue by gbaldeck** [s-panferov/awesome-typescript-loader#312]
I get the below errors when using version 3.0.0-beta.14 with 
TypeScript 2.20-dev.20161213 
Webpack 2.1.0-beta.27
Webpack-dev-server 2.1.0-beta.12

Reverting back to version 3.0.0-beta.13 fixes the issue.

![image](https://cloud.githubusercontent.com/assets/4185224/21160023/9a66bb9a-c140-11e6-8e45-e3f656aea47f.png)

**Comment by niieani** [comment]
Same problem, I've been experiencing already since beta.13, still present in beta.14.

**Comment by morlay** [comment]
We may add code bellow in each of those files;
```ts
import * as ts from "typescript";
```
Global defines will not work well in other users.

**Comment by s-panferov** [comment]
Should be fixed by https://github.com/s-panferov/awesome-typescript-loader/commit/84640b06a58246c1bb07e7aafdf4d7d45faaa74e

**Comment by morlay** [comment]
the file is "typescript/lib/typescriptServices", it still broken in case-sensitive file system, like Linux in CI.

**Comment by sumbad** [comment]
Hi, I have the same problem with '--allowJs' option. 
beta.17

**Comment by rochapablo** [comment]
Same here...

"awesome-typescript-loader": "^3.0.0-beta.18",

```
[at-loader] node_modules\awesome-typescript-loader\dist\interfaces.d.ts:4:20
    Cannot find name 'ts'.

[at-loader] node_modules\awesome-typescript-loader\dist\interfaces.d.ts:13:23
    Cannot find namespace 'ts'.

[at-loader] node_modules\awesome-typescript-loader\dist\interfaces.d.ts:26:18
    Cannot find namespace 'ts'.

[at-loader] node_modules\awesome-typescript-loader\dist\interfaces.d.ts:28:32
    Cannot find namespace 'ts'.

[at-loader] node_modules\awesome-typescript-loader\dist\paths-plugin.d.ts:31:16
    Cannot find name 'ts'.

[at-loader] node_modules\awesome-typescript-loader\dist\paths-plugin.d.ts:33:14
    Cannot find namespace 'ts'.

[at-loader] node_modules\awesome-typescript-loader\dist\paths-plugin.d.ts:37:41
    Cannot find namespace 'ts'.
```

**Comment by tekacs** [comment]
@s-panferov This issue is still related to case sensitivity, despite your patch - our project can currently only be built on a case-insensitive filesystem due to this bug (the identical project builds or doesn't if I move it between case-insensitive JFS and case-sensitive JFS).

To expand on @rochapablo, the error is as follows:

```
ERROR in [at-loader] node_modules/awesome-typescript-loader/dist/interfaces.d.ts:1:1 
    Cannot find type definition file for 'typescript/lib/typescriptservices'.

ERROR in [at-loader] node_modules/awesome-typescript-loader/dist/interfaces.d.ts:5:20 
    Cannot find name 'ts'.

ERROR in [at-loader] node_modules/awesome-typescript-loader/dist/interfaces.d.ts:14:23 
    Cannot find namespace 'ts'.

ERROR in [at-loader] node_modules/awesome-typescript-loader/dist/interfaces.d.ts:27:18 
    Cannot find namespace 'ts'.

ERROR in [at-loader] node_modules/awesome-typescript-loader/dist/interfaces.d.ts:29:32 
    Cannot find namespace 'ts'.

ERROR in [at-loader] node_modules/awesome-typescript-loader/dist/paths-plugin.d.ts:1:1 
    Cannot find type definition file for 'typescript/lib/typescriptservices'.

ERROR in [at-loader] node_modules/awesome-typescript-loader/dist/paths-plugin.d.ts:32:16 
    Cannot find name 'ts'.

ERROR in [at-loader] node_modules/awesome-typescript-loader/dist/paths-plugin.d.ts:34:14 
    Cannot find namespace 'ts'.

ERROR in [at-loader] node_modules/awesome-typescript-loader/dist/paths-plugin.d.ts:38:41 
    Cannot find namespace 'ts'.

ERROR in [at-loader] node_modules/awesome-typescript-loader/src/defines.d.ts:1:1 
    Cannot find type definition file for 'typescript/lib/typescriptservices'.
Child html-webpack-plugin for "index.html":
       [1] ./templates/handlebars/html-config.js 210 bytes {0} [built]
       [3] ./templates/handlebars/html-chunk.js 197 bytes {0} [built]
       [5] ./templates/handlebars/eq.js 148 bytes {0} [built]
      [23] ./~/html-webpack-plugin/lib/loader.js!./templates/index.html.hbs 2.89 kB {0} [built]
        + 20 hidden modules
```

**Comment by alloy** [comment]
Can confirm that with `allowJS` I get the same errors, downgrading to beta 13 works. Project is [here](https://github.com/alloy/relational-theory) if you need an example.

**Comment by hheexx** [comment]
@s-panferov This should be reopened.
It's not fixed.
