### ISSUE TITLE
Parallel webpack builds fails.

### ISSUE THREAD

**Issue by cvle** [s-panferov/awesome-typescript-loader#323]
When running webpack with multiple configs (=parallel) the build fails with the following messages:

~~~
Unknown message:  { emitResult: 
   { text: '/**\r\n * @license\r\n * Copyright (C) 2016 Chi Vinh Le and contributors.\r\n *\r\n * This software may be modified and distributed under the terms\r\n * of the MIT license. See the LICENSE file for details.\r\n */\r\nimport * as bowser from "bowser";\r\n// bowser id -> caniuse id\r\nvar browserIDMap = {\r\n    msie: "ie",\r\n    msedge: "edge",\r\n    firefox: "firefox",\r\n    chrome: "chrome",\r\n    safari: "safari",\r\n    opera: "opera",\r\n    ucbrowser: "and_uc",\r\n    samsungBrowser: "samsung",\r\n    blackberry: "bb",\r\n    android: "android",\r\n    ios: "ios_saf",\r\n};\r\n/**\r\n * @param {String} ua optional user-agent\r\n */\r\nexport function detectBrowser(ua) {\r\n    var bowserInst = ua ? bowser._detect(ua) : bowser;\r\n    var version = bowserInst.version;\r\n    var bid = "unknown";\r\n    for (var b in browserIDMap) {\r\n        if (bowserInst[b]) {\r\n            bid = browserIDMap[b];\r\n            break;\r\n        }\r\n    }\r\n    // no opera mini support yet: https://github.com/ded/bowser/issues/158\r\n    if (bid === "chrome" && bowserInst.android) {\r\n        bid = "and_chr";\r\n    }\r\n    else if (bid === "safari" && bowserInst.ios) {\r\n        bid = "ios_saf";\r\n    }\r\n    else if (bid === "ie" && bowserInst.windowsphone) {\r\n        bid = "ie_mob";\r\n    }\r\n    // use mobile os version.\r\n    if (bid === "android") {\r\n        version = bowserInst.osversion;\r\n    }\r\n    else if (bid === "ios_saf") {\r\n        version = bowserInst.osversion;\r\n    }\r\n    return { id: bid, version: version };\r\n}\r\nexport var currentBrowser = detectBrowser();\r\n//# sourceMappingURL=browser.js.map',
     sourceMap: '{"version":3,"file":"browser.js","sourceRoot":"/home/travis/build/wikiwi/caniuse-support/","sources":["src/browser.ts"],"names":[],"mappings":"AAAA;;;;;;GAMG;AAEH,OAAO,KAAK,MAAM,MAAM,QAAQ,CAAC;AAUjC,0BAA0B;AAC1B,IAAM,YAAY,GAAgC;IAChD,IAAI,EAAE,IAAI;IACV,MAAM,EAAE,MAAM;IACd,OAAO,EAAE,SAAS;IAClB,MAAM,EAAE,QAAQ;IAChB,MAAM,EAAE,QAAQ;IAChB,KAAK,EAAE,OAAO;IACd,SAAS,EAAE,QAAQ;IACnB,cAAc,EAAE,SAAS;IACzB,UAAU,EAAE,IAAI;IAChB,OAAO,EAAE,SAAS;IAClB,GAAG,EAAE,SAAS;CACf,CAAC;AAEF;;GAEG;AACH,MAAM,wBAAwB,EAAW;IACvC,IAAM,UAAU,GAAG,EAAE,GAAG,MAAM,CAAC,OAAO,CAAC,EAAE,CAAC,GAAG,MAAM,CAAC;IACpD,IAAI,OAAO,GAAG,UAAU,CAAC,OAAO,CAAC;IACjC,IAAI,GAAG,GAAc,SAAS,CAAC;IAC/B,GAAG,CAAC,CAAC,IAAM,CAAC,IAAI,YAAY,CAAC,CAAC,CAAC;QAC7B,EAAE,CAAC,CAAC,UAAU,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC;YAClB,GAAG,GAAG,YAAY,CAAC,CAAC,CAAC,CAAC;YACtB,KAAK,CAAC;QACR,CAAC;IACH,CAAC;IACD,sEAAsE;IACtE,EAAE,CAAC,CAAC,GAAG,KAAK,QAAQ,IAAI,UAAU,CAAC,OAAO,CAAC,CAAC,CAAC;QAC3C,GAAG,GAAG,SAAS,CAAC;IAClB,CAAC;IAAC,IAAI,CAAC,EAAE,CAAC,CAAC,GAAG,KAAK,QAAQ,IAAI,UAAU,CAAC,GAAG,CAAC,CAAC,CAAC;QAC9C,GAAG,GAAG,SAAS,CAAC;IAClB,CAAC;IAAC,IAAI,CAAC,EAAE,CAAC,CAAC,GAAG,KAAK,IAAI,IAAI,UAAU,CAAC,YAAY,CAAC,CAAC,CAAC;QACnD,GAAG,GAAG,QAAQ,CAAC;IACjB,CAAC;IAED,yBAAyB;IACzB,EAAE,CAAC,CAAC,GAAG,KAAK,SAAS,CAAC,CAAC,CAAC;QACtB,OAAO,GAAG,UAAU,CAAC,SAAS,CAAC;IACjC,CAAC;IAAC,IAAI,CAAC,EAAE,CAAC,CAAC,GAAG,KAAK,SAAS,CAAC,CAAC,CAAC;QAC7B,OAAO,GAAG,UAAU,CAAC,SAAS,CAAC;IACjC,CAAC;IACD,MAAM,CAAC,EAAE,EAAE,EAAE,GAAG,EAAE,OAAO,SAAA,EAAE,CAAC;AAC9B,CAAC;AAED,MAAM,CAAC,IAAM,cAAc,GAAG,aAAa,EAAE,CAAC"}',
     declaration: undefined },
~~~

Check out the build log here: 
https://travis-ci.org/wikiwi/caniuse-support/jobs/184193513

And the configuration here:
https://github.com/wikiwi/caniuse-support/blob/7563133e568f3f0f4c5742d25276d8d21a45dcd0/webpack.config.js

I am using version 3.0.0-beta.17 and webpack version 2.2.0-rc.0.

Running them sequentially works without issues.

**Comment by pselden** [comment]
I think i have a similar issue although it is when running multiple instances of awesome-typescript-loader in a single configuration.

**Comment by rjokelai** [comment]
I'm having a similar issue with multi-compiler webpack configurations. When disabling one or the other, everything works fine. `instance` option has no effect

**Comment by davidspiess** [comment]
Same problem here with webpack 1

**Comment by sanex3339** [comment]
same problem

**Comment by vtabary** [comment]
I had this problem (3.0.0-beta.17). I fixed it, for now, by using the version 3.0.0-beta.13.

I'm using webpack 2.2.0-rc3

And my tsconfig.json contains : 
```
  "awesomeTypescriptLoaderOptions": {
    "forkChecker": true,
    "useWebpackText": true
  },
```

And I installed the CheckerPlugin as mentionned here https://github.com/s-panferov/awesome-typescript-loader#configuration

Hope this will help

**Comment by FrozenPandaz** [comment]
I have this same issue with webpack 2.2.0-rc3 on Windows and the node(boron) Docker Container

**Comment by georgiosd** [comment]
Same problem here with beta18, workaround above works.

**Comment by JohnLouderback** [comment]
Same problem here

**Comment by ocombe** [comment]
Same thing here, rolling back to beta 13 until then

**Comment by faddee** [comment]
@ThaNarie way worked. It actually speed up my build time so I might even keep it that way.

**Comment by inzerceubytovani** [comment]
Same problem appears when using array in module exports like:

```
module.exports = [
    webpackMerge({}, defaultConfig, commonConfig, clientConfig),
    webpackMerge({}, defaultConfig, commonConfig, serverConfig)
  ];
```

**Comment by s-panferov** [comment]
This is already fixed in master. Release will be ready soon.

**Comment by JohnLouderback** [comment]
@s-panferov Any news? Is the release still happening shortly?

**Comment by inzerceubytovani** [comment]
Look it works now. Great job, thanks!

**Comment by vlavellauruit** [comment]
What version of webpack are you running? I'm having the save issue with the 2.2.1 version
