### ISSUE TITLE
Upgrade from v3.0.8 to v3.1.0 causes "Cannot read property[0] of undefined" error in runtime.ts

### ISSUE THREAD

**Issue by FastAndFluid** [s-panferov/awesome-typescript-loader#390]
Child process failed to process the request:  TypeError: Cannot read property '0' of undefined
    at D:\myProject\node_modules\awesome-typescript-loader\src\checker\runtime.ts:413:29
    at Array.map (native)
    at processDiagnostics (D:\myProject\node_modules\awesome-typescript-loader\src\checker\runtime.ts:409:14)
    at D:\myProject\node_modules\awesome-typescript-loader\src\checker\runtime.ts:475:21
    at Object.send (D:\myProject\node_modules\awesome-typescript-loader\src\checker\runtime.ts:27:21)
    at Checker.req (D:\myProject\node_modules\awesome-typescript-loader\src\checker\checker.ts:101:21)
    at Checker.getDiagnostics (D:\myProject\node_modules\awesome-typescript-loader\src\checker\checker.ts:136:21)
    at Compiler.<anonymous> (D:\myProject\node_modules\awesome-typescript-loader\src\instance.ts:403:32)
    at next (D:\myProject\node_modules\tapable\lib\Tapable.js:140:14)
    at Compiler.<anonymous> (D:\myProject\node_modules\webpack\lib\CachePlugin.js:61:4)

**Comment by s-panferov** [comment]
Sorry for this, fixed in awesome-typescript-loader@3.1.1

**Comment by FastAndFluid** [comment]
Still happening in 3.1.1 for me, together with new error:
ERROR in [at-loader] TS5052: Option 'declarationDir' cannot be specified without specifying option 'declaration'.
